### ISSUE TITLE
just for persian

### ISSUE THREAD

**Issue by Monirzadeh** [mrostd/VazirmatnRegularMagisk#1]
Hi
Module change English font too.
Is it possible for you to just change persian character font?

**Comment by mrostd** [comment]
> Hi Modul change English font too. Is it possible for you to just change persian character font?

Hi @Monirzadeh 

I've released a new version of the Module. In this update, I have ensured that only Persian character font is modified, and Roboto-Regular font should no longer be affected.

To resolve the issue, please follow these steps:

1. Remove the Previous Module

2. Restart Your Device

3. Install the New Module

4. Restart Your Device Again.
