### ISSUE TITLE
vazir variable

### ISSUE THREAD

**Issue by Monirzadeh** [mrostd/VazirmatnRegularMagisk#3]
vazir has a variable version (that have bold etc)
can we have vazir with all of them instead of just Regular?
so bold will use original vazir bold version instead of android make that bold.

**Comment by mrostd** [comment]
> vazir has a variable version (that have bold etc)
> can we have vazir with all of them instead of just Regular?
> so bold will use original vazir bold version instead of android make that bold.

Hi @Monirzadeh 
I’m not sure if using variable fonts as a Magisk module is possible, or maybe I don’t have enough knowledge about it and I need to try it, but I think it’s unlikely. However, if you use the latest version of the module, you can easily see the bold font as well.

**Comment by mrostd** [comment]
> vazir has a variable version (that have bold etc)
> can we have vazir with all of them instead of just Regular?
> so bold will use original vazir bold version instead of android make that bold.

Hi @Monirzadeh 
I’m not sure if using variable fonts as a Magisk module is possible, or maybe I don’t have enough knowledge about it and I need to try it, but I think it’s unlikely. However, if you use the latest version of the module, you can easily see the bold font as well.
Also, the font module uses the "Vazirmatn bold font" to display the bold text and android doesn't make that bold. In fact, the Vazirmatn bold font is included in the module along with the regular font.
